
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter_template/features/term_conditions/domain/entities/term_conditions_entity.dart';

part 'term_conditions_model.freezed.dart';
part 'term_conditions_model.g.dart';

@freezed
abstract class TermConditionsModel with _$TermConditionsModel {
  @JsonSerializable(fieldRename: FieldRename.snake, explicitToJson: true)
  const factory TermConditionsModel({
    required int id,
    
  }) = _TermConditionsModel;

  factory TermConditionsModel.fromJson(Map<String, Object?> json) =>
      _$TermConditionsModelFromJson(json);

 // This will be implemented in all concrete classes generated by Freezed  
  const TermConditionsModel._(); 
  
   TermConditionsEntity asEntity() => TermConditionsEntity(
        id: id,
    );

}
