import 'package:flutter_template/features/auth/domain/entities/login_entity.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'login_response_model.freezed.dart';
part 'login_response_model.g.dart';

@freezed
abstract class LoginResponseModel with _$LoginResponseModel {
  const factory LoginResponseModel({@JsonKey(name: 'jwt') required String jwtToken}) =
      _LoginResponseModel;

  factory LoginResponseModel.fromJson(Map<String, dynamic> json) =>
      _$LoginResponseModelFromJson(json);

  // This will be implemented in all concrete classes generated by Freezed
  const LoginResponseModel._();

  LoginEntity asEntity() {
    return LoginEntity(jwtToken: jwtToken);
  }
}
