import 'package:flutter_template/features/auth/domain/entities/user_entity.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'user_model.freezed.dart';
part 'user_model.g.dart';

@freezed
abstract class UserModel with _$UserModel {
  @JsonSerializable(fieldRename: FieldRename.snake, explicitToJson: true)
  const factory UserModel({required String id, required String name, required String accessToken}) =
      _UserModel;

  factory UserModel.fromJson(Map<String, Object?> json) => _$UserModelFromJson(json);

  // This will be implemented in all concrete classes generated by Freezed
  const UserModel._();

  UserEntity asEntity() => UserEntity(id: id, name: name, accessToken: accessToken);
}
